apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: hotel-app
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/emt_lab?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CET"
  SPRING_DATASOURCE_USERNAME: "emt"